#!/bin/bash

bat_capacity=$(cat /sys/class/power_supply/BAT0/capacity)

if [ $bat_capacity -lt 15 ]
then
	battery_icon=" "
elif [ $bat_capacity -lt 35 ] && [ $bat_capacity -ge 15 ]
then
	battery_icon=" "
elif [ $bat_capacity -lt 60 ] && [ $bat_capacity -ge 35 ]
then
	battery_icon=" "
elif [ $bat_capacity -lt 90 ] && [ $bat_capacity -ge 60 ]
then
	battery_icon=" "
else
	battery_icon=" "
fi

echo "$battery_icon$bat_capacity%"
